#+title: NIXOS Configuration
*THIS README IS OUT OF DATE*

Here is my nixos configuration. It uses home manager to configure programs and is based around the hosts in the host directory, which pull in home manager modules from ~/user~ and system configuration modules from ~/system~. I aim to make this installable with one command at some point, and to work on non-nixos systems, but it is not there yet.

* TODO Install

* Other stuff
Most of the stuff in here is pretty standard, the only thing of interest is the script I use to re-colour the wallpaper to match the stylix theme colours, which can be found in file:./user/style/default.nix

* Credits
Credits go to these projects which I have made use of extensively as reference or made use of in these dots.

+ https://gitlab.com/librephoenix/nixos-config :: The structure of this configuration is based around this, and has been an invaluable resource.
+ https://github.com/Aylur/dotfiles :: Was very useful as reference when setting up waybar.
+ https://github.com/soulhotel/FF-ULTIMA :: Used to make firefox beautiful.
