on:
  pull_request:
  push:

jobs:
  flake-checker:
    name: flake-checker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3
      - name: Check flake
        run: nix flake check --keep-going --log-format raw >> $GITHUB_STEP_SUMMARY
