name: Flake Checker
on:
  pull_request:
  push:

jobs:
  flake_checker:
    name: Flake checker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SETTINGS_PRIVATE_KEY  }}
      - name: Check flake
        run: nix flake check --keep-going

